name: Deploy

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '*'
jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    needs: test
    runs-on: ubuntu-latest

    environment:
      name: development

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3

    - name: Install Composer dependencies
      run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Replace .env values
      run: |
        sed -i 's|APP_NAME=.*|APP_NAME=${{ vars.APP_NAME }}|' .env
        sed -i 's|APP_ENV=.*|APP_ENV=${{ vars.APP_ENV}}|' .env
        sed -i 's|APP_KEY=.*|APP_KEY=${{ secrets.APP_KEY }}|' .env
        sed -i 's|APP_DEBUG=.*|APP_DEBUG=${{ vars.APP_DEBUG }}|' .env
        sed -i 's|DB_CONNECTION=.*|DB_CONNECTION=${{ vars.DB_CONNECTION }}|' .env
        sed -i 's|# DB_HOST=.*|DB_HOST=${{ secrets.DB_HOST }}|' .env
        sed -i 's|# DB_PORT=.*|DB_PORT=${{ secrets.DB_PORT }}|' .env
        sed -i 's|# DB_DATABASE=.*|DB_DATABASE=${{ secrets.DB_DATABASE }}|' .env
        sed -i 's|# DB_USERNAME=.*|DB_USERNAME=${{ secrets.DB_USERNAME }}|' .env
        sed -i 's|# DB_PASSWORD=.*|DB_PASSWORD=${{ secrets.DB_PASSWORD }}|' .env

    - name: Insert DO variables into .env
      run: |
        echo "DO_SPACES_KEY=${{ secrets.DO_SPACES_KEY }}" >> .env
        echo "DO_SPACES_SECRET=${{ secrets.DO_SPACES_SECRET }}" >> .env
        echo "DO_SPACES_ENDPOINT=${{ secrets.DO_SPACES_ENDPOINT }}" >> .env
        echo "DO_SPACES_REGION=${{ secrets.DO_SPACES_REGION }}" >> .env
        echo "DO_SPACES_BUCKET=${{ secrets.DO_SPACES_BUCKET }}" >> .env
        echo "DO_SPACES_IMAGE_PATH=${{ secrets.DO_SPACES_IMAGE_PATH }}" >> .env

    - name: Synchronize Files To Server
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        args: --exclude-from=excludesFile
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.SSH_USERNAME }}
        TARGET: ${{ secrets.DEPLOY_PATH}}

    - name: Run Remote/Artisan Commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            cd ${{ secrets.DEPLOY_PATH }}
            php artisan migrate --force
            php artisan optimize